---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This site is for further exploring symmetric covariance decomposition methods.  

Main takeways thus far (updated June 24):  
  
* symEBcovMF with backfit with point-exponential prior also does relatively well in the tree setting. However, the representation is not fully sparse (We also see this with GBCD and symEBcovMF with the point-Laplace plus splitting initialization). I suspect this is due to the model misspecification with regards to the noise. The corresponding analysis is [here](symebcovmf_point_exp_backfit_tree.html).    

* symEBcovMF backfit initialized with the point-Laplace plus splitting strategy does relatively well in the tree setting. One observation is the representation is not fully sparse; some of the factors have small loadings in other populations alongside the main component. The corresponding analysis is [here](symebcovmf_laplace_split_init_tree_exploration.html).       

* When applying symEBcovMF with point-Laplace prior in the tree setting, the greedy method does not find the sparse representation. However, if you backfit for long enough, e.g. 20,000 iterations, symEBcovMF eventually will find the sparse representation. This behavior is also seen in flashier and EBCD. The corresponding analysis is [here](symebcovmf_laplace_exploration.html)  
* I think the greedy methods do not find the sparse representation because $F$ is not exactly orthogonal (I generate the data matrix $Y$ as $Y = LF' + E$ where $F_{ij} \overset{i.i.d.}{\sim} N(0,2^2)$). It seems like the method is picking up on correlations between the factors. My investigation of this can be found [here](symebcovmf_laplace_model_exploration.html)  
* Flashier's backfit is a lot faster than symEBcovMF's backfit because of its extrapolation technique  
  
* For symEBcovMF, refitting the lambda values after a new factor is added helps improve the fit. This is seen in the balanced, nonoverlapping analysis [here](symebcovmf_bal_nonoverlap.html). It can also help the method find a more complete representation. This is especially apparent in the tree setting analysis [here](symebcovmf_tree.html).  
* For the sparse overlapping setting, the method performs better when the Kmax parameter is set to a larger number. This is seen in the analysis [here](symebcovmf_overlap.html).  

symEBcovMF analyses:    
  
* Exploration of [symEBcovMF in the balanced nonoverlapping setting](symebcovmf_bal_nonoverlap.html)  
* Exploration of [symEBcovMF in the tree setting](symebcovmf_tree.html)  
* Exploration of [generalized binary vs pt-exp symEBcovMF in the tree setting](symebcovmf_tree_exploration.html)   
* Exploration of [different binary priors in tree setting](symebcovmf_binary_prior_tree_exploration.html)    
* Exploration of [symEBcovMF backfit in the tree setting](symebcovmf_point_exp_backfit_tree.html)   
* Exploration of [symEBcovMF in the unbalanced nonoverlapping setting](unbal_nonoverlap.html)  
* Further exploration of [symEBcovMF in the unbalanced nonoverlapping setting](unbal_nonoverlap_exploration.html)  
* Exploration of [symEBcovMF backfit in the unbalanced nonoverlapping setting](unbal_nonoverlap_backfit.html)  
* Exploration of [symEBcovMF in the sparse, overlapping setting](symebcovmf_overlap.html)   
* Exploration of [symEBcovMF backfit in the sparse, overlapping setting](symebcovmf_overlap_backfit.html)    
* Exploration of [symEBcovMF in the null setting](symebcovmf_null.html)  

Analyses related to initialization:  
  
* Exploration of [generalized binary symEBcovMF with point exponential initialization](symebcovmf_point_exp_init.html)  
* Exploration of [generalized binary symEBcovMF backfit initialized with point exponential](symebcovmf_gb_point_exp_backfit.html)   
* Exploration of [point exponential symEBcovMF backfit initialized with point laplace plus splitting](symebcovmf_laplace_split_init_tree.html)    
* Exploration of [point exponential symEBcovMF backfit initialized with point laplace plus splitting part 2](symebcovmf_laplace_split_init_tree_exploration.html)  
* Exploration of [point laplace symEBcovMF backfit in tree setting](symebcovmf_laplace_exploration.html)   
* Exploration of [point laplace greedy symEBcovMF in tree setting](symebcovmf_laplace_model_exploration.html)   

Tree residual matrix example:  
  
* Checking [convergence](symebcovmf_gb_tree_exploration.html)  
* Checking [other binary priors](symebcovmf_binary_tree_resid_exploration.html)  
* Checking [orthogonality](symebcovmf_binary_tree_resid_orthog_exploration.html)  
